services:

  protocol:
    class: Chat\Kernel\Protocol\PostProtocol
    calls:
      - [setLogger, ['@logger']]

  pdo:
    class: Chat\Util\DB\MysqlPdoWrapper
    arguments:
      - '%mysql.host%'
      - '%mysql.port%'
      - '%mysql.username%'
      - '%mysql.password%'
      - '%mysql.database%'

  format:
    class: Chat\Kernel\Protocol\JsonFormat

  logger:
    class: Monolog\Logger
    arguments: ['monolog']