parameters:
  mysql.host: 127.0.0.1
  mysql.port: 3306
  mysql.username: root
  mysql.password: 1
  mysql.database: casket
  redis.scheme: tcp
  redis.host: 127.0.0.1
  redis.port: 6379
  redis.logs: logs_acq
  redis.password: